apiVersion: 1

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: incident-response
        object_matchers:
          - [alertname, "=", "Order lookup 5xx responses"]
        group_by:
          - grafana_folder
          - alertname
        continue: false
